package demoApp;

/**
* demoApp/DemoRandomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 1 November 2016 11:51:49 AM AEDT
*/

public final class DemoRandomHolder implements org.omg.CORBA.portable.Streamable
{
  public demoApp.DemoRandom value = null;

  public DemoRandomHolder ()
  {
  }

  public DemoRandomHolder (demoApp.DemoRandom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = demoApp.DemoRandomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    demoApp.DemoRandomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return demoApp.DemoRandomHelper.type ();
  }

}
