package demoApp;


/**
* demoApp/DemoRandomHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 1 November 2016 11:51:49 AM AEDT
*/

abstract public class DemoRandomHelper
{
  private static String  _id = "IDL:demoApp/DemoRandom:1.0";

  public static void insert (org.omg.CORBA.Any a, demoApp.DemoRandom that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static demoApp.DemoRandom extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (demoApp.DemoRandomHelper.id (), "DemoRandom");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static demoApp.DemoRandom read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DemoRandomStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, demoApp.DemoRandom value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static demoApp.DemoRandom narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof demoApp.DemoRandom)
      return (demoApp.DemoRandom)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      demoApp._DemoRandomStub stub = new demoApp._DemoRandomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static demoApp.DemoRandom unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof demoApp.DemoRandom)
      return (demoApp.DemoRandom)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      demoApp._DemoRandomStub stub = new demoApp._DemoRandomStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
