package demoApp;


/**
* demoApp/DemoRandomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 1 November 2016 11:51:49 AM AEDT
*/

public interface DemoRandomOperations 
{
  String getRandom ();
} // interface DemoRandomOperations
