package demoApp;


/**
* demoApp/DemoRandomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 25 October 2016 10:01:45 PM AEDT
*/

public interface DemoRandomOperations 
{
  String getRandom ();
} // interface DemoRandomOperations
