package demoApp;


/**
* demoApp/DemoRandom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 1 November 2016 11:52:11 AM AEDT
*/

public interface DemoRandom extends DemoRandomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DemoRandom
