package demoApp;


/**
* demoApp/DemoRandom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 25 October 2016 10:01:53 PM AEDT
*/

public interface DemoRandom extends DemoRandomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DemoRandom
