package demoApp;


/**
* demoApp/DemoRandomPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Tuesday, 1 November 2016 11:52:11 AM AEDT
*/

public abstract class DemoRandomPOA extends org.omg.PortableServer.Servant
 implements demoApp.DemoRandomOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getRandom", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // demoApp/DemoRandom/getRandom
       {
         String $result = null;
         $result = this.getRandom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:demoApp/DemoRandom:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DemoRandom _this() 
  {
    return DemoRandomHelper.narrow(
    super._this_object());
  }

  public DemoRandom _this(org.omg.CORBA.ORB orb) 
  {
    return DemoRandomHelper.narrow(
    super._this_object(orb));
  }


} // class DemoRandomPOA
